/**
 * Tests random AI against human.
 */
import {BattleStream, getPlayerStreams} from '../battle-stream';
import {Dex} from '../dex';
import {MyAI} from '../tools/my_ai';
import {RandomPlayerAI} from '../tools/random-player-ai';
import {Player_input} from '../tools/player_input';
// tslint:disable:no-floating-promises
const spec = {
	formatid: "gen7customgame",
};

//Give Alice and Bob two totally arbitary teams which were generated by the random team generator some ways back.

// In the near future, the "', //" will be removed, and so will p1lookup and p2lookup. We need them here for 1v1 though.
const p1spec = {
	name: "Alice",
	team: 'Swellow||flameorb|guts|quickattack,earthquake,swordsdance,facade||85,85,85,85,85,85||||100|]Ledian||leftovers|swarm|toxic,stealthrock,uturn,roost||85,85,85,85,85,85||||100|',//]Malamar||leftovers|contrary|sleeptalk,superpower,rest,knockoff||85,85,85,85,85,85||||10|]Houndoom||houndoominite|flashfire|darkpulse,nastyplot,hiddenpowergrass,fireblast||81,,85,85,85,85||,0,,,,||10|]Victreebel||grassiumz|chlorophyll|powerwhip,knockoff,swordsdance,sleeppowder||85,85,85,85,85,85||||10|]Lugia||leftovers|multiscale|psychic,substitute,toxic,whirlwind||85,,85,85,85,85|N|,0,,,,||10|',
};
const p2spec = {
	name: "Bob",
	team: 'Aggron||leftovers|sturdy|headsmash,heavyslam,aquatail,superpower||85,85,85,85,85,85||||100|]Arceus|arceusfighting|fistplate|multitype|swordsdance,extremespeed,aerialace,dracometeor||85,,85,85,85,85|N|,0,,,,||81|',//]Dragonite||lumberry|multiscale|dragonclaw,firepunch,roost,earthquake||81,85,85,85,85,85||||10|]Uxie||leftovers|levitate|psyshock,yawn,stealthrock,psychic||85,85,85,85,85,85|N|||10|]Cacturne||leftovers|waterabsorb|swordsdance,seedbomb,suckerpunch,spikes||85,85,85,85,85,85||||10|]Druddigon||lifeorb|sheerforce|dragontail,suckerpunch,gunkshot,aerialace||85,85,85,85,85,85||||10|',
};

const p1lookup = {
        name: "Alice",
        team: 'Ledian||leftovers|swarm|roost,acrobatics,uturn,toxic||85,85,85,85,85,85||||100|]Swellow||flameorb|guts|protect,bravebird,quickattack,facade||85,85,85,85,85,85||||10|]Malamar||leftovers|contrary|sleeptalk,superpower,rest,knockoff||85,85,85,85,85,85||||10|]Houndoom||houndoominite|flashfire|darkpulse,nastyplot,hiddenpowergrass,fireblast||81,,85,85,85,85||,0,,,,||10|]Victreebel||grassiumz|chlorophyll|powerwhip,knockoff,swordsdance,sleeppowder||85,85,85,85,85,85||||10|]Lugia||leftovers|multiscale|psychic,substitute,toxic,whirlwind||85,,85,85,85,85|N|,0,,,,||10|',
};
const p2lookup = {
        name: "Bob",
        team: 'Arceus|arceusfighting|fistplate|multitype|calmmind,shadowclaw,aerialace,judgment||85,,85,85,85,85|N|,0,,,,||81|]Aggron||aggronite|sturdy|roar,heavyslam,rockslide,toxic||85,85,85,85,85,85||||10|]Dragonite||lumberry|multiscale|dragonclaw,firepunch,roost,earthquake||81,85,85,85,85,85||||10|]Uxie||leftovers|levitate|psyshock,yawn,stealthrock,psychic||85,85,85,85,85,85|N|||10|]Cacturne||leftovers|waterabsorb|swordsdance,seedbomb,suckerpunch,spikes||85,85,85,85,85,85||||10|]Druddigon||lifeorb|sheerforce|dragontail,suckerpunch,gunkshot,aerialace||85,85,85,85,85,85||||10|',
};


function spec_to_dict(spec: anyObject, name: string) {
	let pokemonNames = spec.team.split('|');
	pokemonNames = [name + ": " + pokemonNames[0], name + ": " + pokemonNames[11].slice(1), name + ": " + pokemonNames[22].slice(1), name + ": " + pokemonNames[33].slice(1), name + ": " + pokemonNames[44].slice(1), name + ": " + pokemonNames[55].slice(1)];
	let pokemonIndices = [0,0,0,0,0,0]
	let retval = {};
	for (let i in [0,1,2,3,4,5]) {
		for (let j in [0,1,2,3,4,5]) {
			if (pokemonNames[j] < pokemonNames[i]) {
				pokemonIndices[i] += 1;
			}
		}
		retval[pokemonNames[i]] = pokemonIndices[i];
	}
	return retval;
}

const aliceLookup = spec_to_dict(p1lookup, "p1");
const bobLookup = spec_to_dict(p2lookup, "p2");

//Set up the streaming infrastructure.
let streams = getPlayerStreams(new BattleStream(), [aliceLookup, bobLookup]);

//Debug is false.
const p1 = new RandomPlayerAI(streams.p1, {}, false, "Alice");
const p2 = new Player_input(streams.p2, {}, false, "HughMann");
//const p2 = new RandomPlayerAI(streams.p2, {}, false, "Bob");

//Tell the players to start up.
p1.start();
p2.start();

/*(async () => {
        let chunk;
        // tslint:disable-next-line no-conditional-assignment
        while ((chunk = await streams.omniscient.read())) {
                console.log(chunk);
        }
})();*/

streams.omniscient.write(`>start ${JSON.stringify(spec)}
>player p1 ${JSON.stringify(p1spec)}
>player p2 ${JSON.stringify(p2spec)}`);

